### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by okonet** [postcss/brand#10]
This repository is missing required fonts. I suggest the logo should be converted to curves or the required font should be included in the repository. This opens the second issue: does this font license allows us its usage and distribution? I've opened a separate issue for it: #9

**Comment by stephenway** [comment]
Each text layer has an outlined layer that is active, while the text layer is hidden. So you can view the file without the font.

**Comment by okonet** [comment]
Yeah, I found this out. Thanks!
