### ISSUE TITLE
Simplify logo paths

### ISSUE THREAD

**Issue by okonet** [postcss/brand#11]
Right now logo contains _a lot_ of points and can be simplified signigicantly without losing a lot of details:

<img width="782" alt="2016-01-13 at 20 48" src="https://cloud.githubusercontent.com/assets/11071/12305894/44448aaa-ba37-11e5-8a74-35d388c50e6f.png">

See a very nice article about minifying SVGs: https://medium.com/@larsenwork/optimising-svgs-for-web-use-part-1-67e8f2d4035#.4xd4b5dx9

**Comment by ai** [comment]
Yeapp, we could try, but it is a low priority task, I think. Because we win only a file size.

**Comment by stephenway** [comment]
Agreed @ai
