### ISSUE TITLE
logo licence

### ISSUE THREAD

**Issue by IWANABETHATGUY** [postcss/brand#15]
@ai , hi, we are porting postcss recently, and I am wonder if the logo of postcss is free to use, or it is protected.We may want to use postcss logo as part of our new logo。

**Comment by ai** [comment]
The license is CC-BY. You can use it if it will be clear that it is PostCSS logo.

**Comment by IWANABETHATGUY** [comment]
> The license is CC-BY. You can use it if it will be clear that it is PostCSS logo.

Thanks!
