### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by stephenway** [postcss/brand#3]
Continuation from postcss/postcss.com#14

**Comment by stephenway** [comment]
So I have some round 2 options based on what we discovered yesterday. I went through some sans-serif options with the same format. Century and Poppins seem to feel the most congruent with the round logo symbol. Based on feedback from @ai I came up with a brush script inspired by [his own henna](https://pp.vk.me/c314431/v314431146/4d05/bSv3XtzICu4.jpg) which is awesome and liberating from just looking at a linear order of letters.

Actually having gone through this, I think the Besom option feels most consistent for a logoset as a whole. Style matches like @MoOx seemed to point out earlier on, and it has a unique feel to it.

Bring on the comments! Can't wait to get a solid direction so we can move forward with a new identity for the new site.
![postcss-logo-round-2](https://cloud.githubusercontent.com/assets/38894/12081061/626a441e-b223-11e5-81a0-bcf960e991e8.png)

**Comment by MoOx** [comment]
1 and 2 lgtm.

**Comment by ben-eb** [comment]
Agree with 1 & 2 but might look nicer still if the logo is the same height as the capital letters. Right now it looks off.

**Comment by ai** [comment]
I think Helvetica is too often used. Century and Popins have to big difference between C and S. Nanum is much lighter, than lines in the sign. This is why I take Franklin, because it looks fresh, has same line weight and balanced letters size in “CSS” part.

**Comment by ai** [comment]
Honestly Vyaz too hard to read without understanding of letters sequence. But this experiment is nice. Maybe we can use it latter in PostCSS Shabbash metteup. Thanks @stephenway.

**Comment by stephenway** [comment]
@ai :+1: Sounds good! I'll prep logo deliverables tonight and put together a visual aide for typesetting and spacing on this repo.

:rocket: Chosen logotype is the Franklin Gothic variant:
<img width="377" alt="screen shot 2016-01-03 at 3 55 10 pm" src="https://cloud.githubusercontent.com/assets/38894/12081571/63559c52-b232-11e5-9fce-bca7c5389a15.png">

**Comment by ai** [comment]
@stephenway yeap “st” part looks like too narrow.

**Comment by stephenway** [comment]
@ai I loosened up the "st" area kerning and built out some deliverables, would like to close this issue and start adding this to the repo if that's ok with you?
![postcss-logo-horizontal](https://cloud.githubusercontent.com/assets/38894/12084458/923b3078-b268-11e5-8e66-5e6f31351376.png)
![postcss-logo-vertical](https://cloud.githubusercontent.com/assets/38894/12084459/9572238c-b268-11e5-8a98-329846095900.png)
![postcss-logo-blackonwhite](https://cloud.githubusercontent.com/assets/38894/12084463/9c2cb692-b268-11e5-9ab6-03c5a4d43680.png)
![postcss-logo-whiteonblack](https://cloud.githubusercontent.com/assets/38894/12084466/a258f724-b268-11e5-8b23-dbe537f67cf1.png)
![postcss-logo-colors](https://cloud.githubusercontent.com/assets/38894/12084471/a75dc0f6-b268-11e5-97fa-e186e9a2a879.png)
![postcss-logo-space-and-type](https://cloud.githubusercontent.com/assets/38894/12084472/ae5e37b4-b268-11e5-802b-ae1ea9efbd2c.png)
![postcss-logo-alignment](https://cloud.githubusercontent.com/assets/38894/12084473/b18fd56e-b268-11e5-9ded-fcde4ce364be.png)

**Comment by marcustisater** [comment]
That looks awesome, great work @stephenway. I agree with the choice of Franklin Gothic, it's good to try something different then H. Neue.

**Comment by ai** [comment]
@stephenway also we can change red color if you think that it is not so good

**Comment by stephenway** [comment]
@ai I like the red we have, but for my personal taste I always prefer a mix of orange in with the red for more of a French red.
![screen shot 2016-01-04 at 1 00 39 pm](https://cloud.githubusercontent.com/assets/38894/12100374/58adf608-b2e3-11e5-83df-64765bf34cac.png)

**Comment by ai** [comment]
@stephenway yeap, looks much better

**Comment by ai** [comment]
Also maybe we should put few pixels between “CS”, because “SS” have more space?

**Comment by stephenway** [comment]
Updated with new red and more space between "CS"
<img width="882" alt="screen shot 2016-01-05 at 9 15 48 am" src="https://cloud.githubusercontent.com/assets/38894/12121929/f68607a4-b38c-11e5-933a-f78b7aa23130.png">

**Comment by marcustisater** [comment]
That looks fantastic, I really like the new red color.

**Comment by ai** [comment]
Awesome. You did great work.

I will announce it later in PostCSS account.

**Comment by r3nya** [comment]
@stephenway :+1:

**Comment by okonet** [comment]
Sorry for the noise again but I've just stumbled upon my tweet with a photo of @markdalgleish presenting about PostCSS (https://twitter.com/okonetchnikov/status/662340331795587073) and I kind of like what he did with the type in his presentation. 

So I've qickly gave it a try:

![2016-01-18 at 13 14](https://cloud.githubusercontent.com/assets/11071/12391082/79913742-bde5-11e5-818b-aa5f220e4952.png)

And keeping in mind that presentations usually have dark backgrounds and the target audience are  presentation authors, I think this could work pretty well.

BTW this one uses [Source Code Pro](https://github.com/adobe-fonts/source-code-pro)

@stephenway @ai WYT?

**Comment by okonet** [comment]
And this is how it could look on the website

![2016-01-18 at 13 22](https://cloud.githubusercontent.com/assets/11071/12391249/a7e170fc-bde6-11e5-8d93-3783e2a1b1e7.png)

@ai I know you might not like it but give a thought :)

**Comment by MoOx** [comment]
For my concern I like the CamelCased typo (PostCSS)

**Comment by ai** [comment]
I think it is harder to read. Sign is complicated. So when we put text insode, it become more complicated.

Also CamelCased is good for PostCSS name.

**Comment by marcustisater** [comment]
@MoOx and @ai has a very good point. I think we should keep the text separate from the the actual logo itself, it's easier to read and would not to be "confusing" in how we present it. It's difficult to explain but my intentions says no.

However I think the design itself looks pretty neat, I just don't think it's meant for PostCSS.

**Comment by okonet** [comment]
Thanks! These are good points indeed.

**Comment by marcustisater** [comment]
Thank you for the quick drafts, it was not a bad idea - got me thinking :thought_balloon:
