### ISSUE TITLE
CC-BY 4.0 for everyone

### ISSUE THREAD

**Issue by ai** [postcss/brand#4]
@stephenway let’s move logo to CC-BY 4.0 license too to have same license across repo.

**Comment by marcustisater** [comment]
I thought writing content/docs is under CC-BY 4.0. Shouldn't logo be under MIT? Please double check  repos. We use MIT for code and CC-BY 4.0 for docs on postcss.com

**Comment by ai** [comment]
CC is better for any non-code content like art and images.

**Comment by ai** [comment]
I amd talking about this text in README.md:

```
The PostCSS Logo is copyright under the MIT License.

All artwork is copyright under the Attribution 4.0 International License
```

**Comment by marcustisater** [comment]
Ahaa, I see.

**Comment by marcustisater** [comment]
@stephenway any thoughts? otherwise I can set this up asap.

**Comment by stephenway** [comment]
Yea I haven't gotten to this yet, easy change either way. Thanks @marcustisater

**Comment by stephenway** [comment]
Fixed in latest push
