### ISSUE TITLE
Strange line in sign

### ISSUE THREAD

**Issue by ai** [postcss/brand#5]
Sign has strange line inside? Is it broken SVG viewer in GitHub?

/cc @stephenway 

![](http://i.imgur.com/vgbNWUM.png)

**Comment by MoOx** [comment]
Same issue in Sketch. I think that's the SVG.

**Comment by ai** [comment]
@stephenway ping. I want to update logo in every account, I just wait for this line fix.

**Comment by ai** [comment]
@stephenway any updates?

**Comment by stephenway** [comment]
Fixed in latest push.
