### ISSUE TITLE
my version of logo

### ISSUE THREAD

**Issue by krasnovpro** [postcss/brand#6]
![vn2hzz42](https://cloud.githubusercontent.com/assets/886676/12197906/5330dbe6-b61c-11e5-98aa-41b4d6243077.png)

**Comment by ai** [comment]
@stephenway what do you think?

I think previous font is better, because it has no USSR feeling. But maybe we definitely should try more simple logo without hand-write style

**Comment by MoOx** [comment]
I really like what @stephenway did.
I don't like this one.

**Comment by ai** [comment]
@quaritexa I think that design is rational. So could you write some your ideas, why old logo is bad for our tasks and why your logo solves them better?

**Comment by ai** [comment]
@MoOx design is not about what we like. Design is about solving a tasks. This is why we should always be focused on objective, rather than subjective, when we discuss a design questions.

**Comment by MoOx** [comment]
I may not be a designer but I think I have too many reasons in my mind why previous logo + font are better.
In short: this logo don't have a personnality and do not stick in your head.
The font provide a "bloatty" feeling too (and/or USSR feeling like you say).
Anyway, I am just sharing my feeling :)

**Comment by ai** [comment]
@MoOx yeap, current font is better. But we didn't even think about changing a logo. We was focused only on font previous time.

**Comment by stephenway** [comment]
Well said @ai. Our main intention was to define a typeface, not rebrand. This is a bit verbose and without personality. Maybe in the future there will be a time where we look at updating the brand, but I don't see that happening today.

**Comment by marcustisater** [comment]
I agree, we aren't updating the brand and it's too big of a change. Thank you for submitting a logotype anyway, hope you got some good feedback out of it.
