### ISSUE TITLE
Clean SVG

### ISSUE THREAD

**Issue by ai** [postcss/brand#7]
Right now SVG files contains many comments and unnecessary stuff from Skatch.

Let’s use `svgo` to clean them.

@stephenway do you need this meta? I can add a `package.json` with `svgo` here.

**Comment by MoOx** [comment]
Becareful imo. Svgo can be dangerous sometimes.

**Comment by ai** [comment]
Current logo was processed by svgo.

**Comment by TrySound** [comment]
@MoOx What exactly dangerous in it?

**Comment by MoOx** [comment]
You can loose metadata that might be interesting when you will edit the file later.
svgo is good for productions assets, but I think original assets should not be optimized (it's not huge like jpg or png anyway...)

**Comment by stephenway** [comment]
Added svgo gulp task for anyone who wants to use this for web.
