### ISSUE TITLE
Pixel Version for Favicon

### ISSUE THREAD

**Issue by stephenway** [postcss/brand#8]
Continuation of [.com/#40](https://github.com/postcss/postcss.com/issues/40)

We need to draw a pixel version of the logo for a favicon around 32px squared.

**Comment by marcustisater** [comment]
I would prefer to prioritize this for [Milestone 1](https://github.com/postcss/postcss.org/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0) if possible.

**Comment by marcustisater** [comment]
Deadline: 19 Feb.

Can you make that happen before that @stephenway? It would be nice for the first rel.

**Comment by stephenway** [comment]
I'll see what I can do today.

**Comment by ai** [comment]
@stephenway ping =^_^=
