### ISSUE TITLE
Franklin Gothic Book license

### ISSUE THREAD

**Issue by okonet** [postcss/brand#9]
Does this font license allows us using it in this project and (basically) distribute it this way? Also, does it allow us using it on the web-site?

Microsoft links it to http://www.fonts.com/web-fonts in case of web-site usage and to http://catalog.monotype.com/font/itc/itc-franklin-gothic/book.

**Comment by stephenway** [comment]
The logo does not use this font as a web font. Could you explain what the use case is?

**Comment by ai** [comment]
We will use this font as web font in postcss.org

**Comment by stephenway** [comment]
@ai We will need to purchase a we font license in that case. They track Pageviews and pricing starts at $49.

**Comment by okonet** [comment]
Should we look for Google Fonts alternatives before we pay for a license?

**Comment by okonet** [comment]
I also think the Franklin Gothic doesn't fit the logo well (it's just too modern for this alchemy style). But I can imagine this was a conceptuanal decision (old + new == good?)

**Comment by ai** [comment]
Logotype is licensed under CC-BY. So we can use only same free content inside it (license should allow distribution, modification and commercial usage).

So seems like we need to change a font.

**Comment by stephenway** [comment]
@okonet You should check out the original threads where we went through the process of finding the right typeface.

**Comment by okonet** [comment]
@stephenway can you point me there please?

**Comment by stephenway** [comment]
#3

**Comment by stephenway** [comment]
This is what I originally had in mind for web usage because it is very common http://www.cssfontstack.com/Franklin-Gothic-Medium

**Comment by okonet** [comment]
This is the license Google Fonts types are using: http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL Needs to be cvarefully read before jumping into conclusion if it fits CC-BY or not.

See more https://www.google.com/fonts/attribution

**Comment by ai** [comment]
According [Wikipedia](https://en.wikipedia.org/wiki/SIL_Open_Font_License):
- DFSG compatible: Yes
- FSF approved: Yes
- OSI approved: Yes
- Copyleft: Yes

**Comment by stephenway** [comment]
Source Sans Pro shows many similarities to Franklin Gothic and is [free to use](https://www.google.com/fonts/specimen/Source+Sans+Pro). Note: Will adjust kerning on these comps once we have a final decision.

![postcss-logo-horizontal](https://cloud.githubusercontent.com/assets/38894/12278204/9f2bb884-b934-11e5-917d-6f6556ab2db7.png)

**Comment by ai** [comment]
Yeap. It looks like very similar.

What do you think about @okonet idea to use some non-modern font?

**Comment by ai** [comment]
If we will use modern font, Ubuntu is also looks nice. It looks very fresh. Has nice `t` and good `CS` proportions. Can you make this color preview please? :)

**Comment by mxstbr** [comment]
Source Sans Pro :heart:

My favorite font, I use it [everywhere](http://mxstbr.com/)! So nice!

**Comment by stephenway** [comment]
@ai We did explore some non-modern typefaces and they didn't seem right. However I'm still in love with the Besom comp I drew from last round. 
<img width="305" alt="screen shot 2016-01-12 at 2 04 23 pm" src="https://cloud.githubusercontent.com/assets/38894/12278342/70acebee-b935-11e5-9f30-a5db5b50babb.png">
I believe the biggest thing was readability though.

Ubuntu
![postcss-logo-horizontal](https://cloud.githubusercontent.com/assets/38894/12278421/d8800b8e-b935-11e5-9360-68afa6a83468.png)

Being in red, it reminds me a lot of Ubuntu though.

**Comment by ai** [comment]
@stephenway yeap, most of real old fonts looks ridiculous :D.

I love Besom comp so much :D. But we should think objectivly, reading is really too complicated. But I promise to save it and use in some special logos like PostCSS meetups :).

When I opened Google Font last time it was much smaller :(. Really big choice.

After first run I select this fonts. @stephenway do you have some automatically tool to made color preview? If not, I will made a HTML page tomorrow to compare all these fonts (this list is too big to ask someone to make it manually):

Source Sans Pro, Ubuntu Quattrocento Sans, Istok Web, EB Garamond, Cantarell, Cinzel, Kreon, Neucha, Arbutus Slab, Belleza, Quando, Balthazar, Brawler, Caesar Dressing, Skranji, IM Fell English SC, Junge, Expletus Sans, Patrick Hand SC, Delius Swash Caps, Kite One, Sniglet, Cagliostro, Aladin, Overlock SC, IM Fell DW Pica SC, Artifika, Port Lligat Sans, Mandali, Kurale

**Comment by stephenway** [comment]
@ai I'll take a look at these, but I don't have a tool that does all of that online. Thanks for taking the time to look at some more options.

**Comment by okonet** [comment]
I think that the logo does not need a specific font. It works perfectly well with any modern font set in black IMO. I've tried a few different OSS fonts with the sign:

![2016-01-13 at 11 32](https://cloud.githubusercontent.com/assets/11071/12291743/5d0cd73e-b9e9-11e5-8e42-a98c18b309a1.png)

I personally like `IM FELL DW Pica` more than others since it resembles to the ancient / rome era somehow but it might be too much :) 

Another option would be to create a unique script (self-drawned) which should fit the logo. Right now it looks very disconnected in style. Something like `Besom` but more readable?

**Comment by ai** [comment]
I agree, that we shouldn't force only one font.

But having logotype images with project name is good. Many slide and news authors are too lazy and they will be happy for some solution.

**Comment by okonet** [comment]
Makes sense to me, but right now it looks like PostCSS is too specific about the font (2 colors, special font etc.). Also, is it that important that logo has a project name in it? I'd encourage to use just the sign for presentations etc. because people still will be making slides with their fonts and it might conflict with them.

**Comment by ai** [comment]
I always prefer common sense rather than rules.

At least current logo has no big connection with project name. So it is OK to use logo without name (our stickers has no name).

It is only for cases, when user just out of box solution.

**Comment by stephenway** [comment]
I think we are getting a little off topic. The goal of this issue is to come up with a typeface that is open licensed. The logo symbol can be used independently of the logo type just like most other brands.

**Comment by okonet** [comment]
@stephenway it wasn't clear to me after checking out this repo. I think we should communicate that in a better way. Just saying.

**Comment by stephenway** [comment]
Yes better docs are coming. Thanks

**Comment by okonet** [comment]
@ai @stephenway what about something like this?

<img width="162" alt="2016-01-13 at 20 38" src="https://cloud.githubusercontent.com/assets/11071/12305562/b525e54a-ba35-11e5-91dd-e6faf2689f63.png">

**Comment by okonet** [comment]
Here is a nice example of some "alchemic" script:

![font](http://alchemyfraternitas.ru/media/photologue/photos/griemiller06.jpg)

**Comment by okonet** [comment]
But I agree that readability is an issue here

**Comment by stephenway** [comment]
I can't read any of that.

The alternate Besom you came up with isn't consistent. Letters are stacked in Css and not Post. Even then it doesn't seem to hold it's own in that orientation.

**Comment by okonet** [comment]
I didn't touch CSS since I don't have the font. Was just an idea.

**Comment by marcustisater** [comment]
I don't want to sound boring and ruin the whole alchemic feeling but we should really use https://www.google.com/fonts/specimen/Source+Sans+Pro for this case.

**Comment by ai** [comment]
Yeap, we can always use Source Sans Pro. But first I want to test that fonts too. I think we have day our two.

**Comment by marcustisater** [comment]
Yeah, no rush.

**Comment by ai** [comment]
I made a big preview of my choosen fonts: http://codepen.io/iskin/full/YwrxvE/

Thoughs:
1. Ubuntu letters look like more active than in Source Sans Pro.
2. Expletus Sans has same missed part in `t`, so it is closer to logo.
3. Patrick Hand SC is hand-written as logo.
4. Cagliostro looks like very active (because of `S` angle).
5. IM Fell English SC loooks more close to logo than IM Fell DW Pica SC. I think because its letters is not in right positiom, so it is more chaotic as logo.
6. Caesar Dressing and Skranji looks promissing.

I will review them tomorrow after a sleep. But my current favorites are: Ubuntu, IM Fell DW Pica SC, Caesar Dressing, Skranji.

**Comment by ai** [comment]
BTW, I make a build too, so I can add your fonts to competition.

**Comment by ai** [comment]
@stephenway what is your thoughts about red and black version?

![red](http://i.imgur.com/vfG1I2c.png)

**Comment by stephenway** [comment]
@ai Seems to work, however the contrast difference seems to distract my eye. Maybe try a lighter black, or darker red?

**Comment by okonet** [comment]
@ai did you try Fira Sans? Last mockup for the home page uses it. 

From your list I prefer Kreon. 

What about the text in black? It would make things easier and fit better how it looks now on github

**Comment by ai** [comment]
@okonet yeap, I missed Fira Sans. It looks soo close to Ubuntu. Same feelings, but more standard.

![](http://i.imgur.com/Br6IJET.png)

**Comment by ai** [comment]
Anyway, let’s think in categories :D.
1. Sans.
2. Serif.
3. Caesar Dressing.

@stephenway @okonet What is your thoughts in this categories?

**Comment by okonet** [comment]
Caesar doesn't fit at all IMO. I think serif has more connection to the logo. And taking a second look, I like the IM Fell English even better now :)

I still think there should not be just one font. We could choose one for easier distribution but we shouldn't be very sensitive about it. That's why I think it should be set in all black.

**Comment by ai** [comment]
@okonet yeap, I think serif is better. Should in horizontal logotype font letters have same lines weight as in logo? 

@jonathantneal what do you think about sans vs. serif? What serif font do you prefer?

**Comment by stephenway** [comment]
Kreon LGTM

**Comment by marcustisater** [comment]
Fira Sans LGTM but Kreon has more of the alchemy style we are looking for.

However I would prefer a web safe font but we can optimize rendering later.

**Comment by ai** [comment]
Becuase we have no ideal font and anyway it is just a recommendation, I will finish this task with picking one font on my taste (sometimes any solution is better than spending time in choicing :) ).

Let’s take **Kreon** to have some solution.

Anyway later we will think about better logo and maybe will buy custom lettering.

@jonathantneal can you regenerate build files (I have no Mac OS X to run a Sketch).

**Comment by ai** [comment]
Oops, sorry @jonathantneal I mean a @stephenway

**Comment by stephenway** [comment]
@ai I'll definitely regenerate the build this week. Thanks
